# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
_ssh_auth_save() {
    ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh-auth-sock.$HOSTNAME"
    if [ ! -L "$HOME/.ssh/ssh-auth-sock.$HOSTNAME" ]; then
        echo "Failed to create ssh_auth_sock symlink"
    fi
}
alias tmux='export HOSTNAME=$(hostname) ; _ssh_auth_save ; tmux'
